version: "3.8"

volumes:
  data:
  letsencrypt:

services:
  nginx-proxy_app:
    image: jc21/nginx-proxy-manager:2.9.12
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 81:81
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt

networks:
  default:
    name: nginx-proxy