version: "2"

volumes:
  db:
  minio:

services:
  db:
    image: bitnami/postgresql:14.1.0-debian-10-r31
    ports:
      - 5432:5432
    volumes:
      - db:/bitnami/postgresql
      - ./initdb:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRESQL_USER=webbde
      - POSTGRESQL_PASSWORD=webbde
      - POSTGRESQL_DATABASE=webbde

  minio:
    image: "bitnami/minio:latest"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ACCESS_KEY=minio-access-key
      - MINIO_SECRET_KEY=minio-secret-key
    networks:
      - default
    volumes:
      - minio:/data

networks:
  default:
    name: preprod-web-bde
