apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment
spec:
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
        - name: back
          image: ghcr.io/roxxas96/back-web-bde:main
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 4000
          env:
            - name: DATABASE_URI
              value: postgresql://webbde:webbde@postgres-postgresql-ha-pgpool.default.svc.cluster.local:5432/webbde
            - name: API_HOST
              value: localhost:8081
            - name: FASTIFY_ADDRESS
              value: "0.0.0.0"
            - name: FASTIFY_PREFIX
              value: /api
            - name: FASTIFY_LOG_LEVEL
              value: info
            - name: FASTIFY_PORT
              value: "4000"
