apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: bitnami/postgresql:14.1.0-debian-10-r31
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRESQL_PASSWORD
              value: webbde
            - name: POSTGRESQL_USER
              value: webbde
            - name: POSTGRESQL_DATABASE
              value: webbde
